project:
  type: website
  output-dir: docs
  
website:
  title: "Hongjun Kim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Traveling.qmd
      - Portfolio1.qmd
      
format:
  html:
    theme: LUX
    css: styles.css
    toc: true

editor: visual

